apiVersion: lifecycle.keptn.sh/v1beta1
kind: KeptnAppContext
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  preDeploymentEvaluations:
    - app-pre-deploy-eval
  postDeploymentTasks:
    - post-deployment-task