apiVersion: lifecycle.keptn.sh/v1beta1
kind: KeptnTaskDefinition
metadata:
  name: post-deployment-task
  namespace: podtato-kubectl
spec:
  function:
    inline:
      code: |
            let message: string = 'Succesfully Deployed!';
            console.log(message);
    